# Table of Contents
- [Data Preprocessing](#data-preprocessing)
  - [Missing value treatment](#missing-value-treatment)
  - [Treatment of categorical variables](#treatment-of-categorical-variables)
    - [Treatment of 'ID' column](#treatment-of-id-column)
    - [Treatment of ZIPCode variable](#treatment-of-zipcode-variable)
    - [Feature engineering (if needed)](#feature-engineering-if-needed)
    - [OneHot Encoding](#onehot-encoding)
  - [Multicollinearity Treatment](#multicollinearity-treatment)
  - [Outliers](#outliers)
  - [Data Imbalance](#data-imbalance)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Load the dataset
df_orig = pd.read_csv('../data/raw/Loan_Modeling.csv')
df = df_orig.copy()

## Data Preprocessing

* Missing value treatment
* Feature engineering (if needed)
* Outlier detection and treatment (if needed)
* Preparing data for modeling
* Any other preprocessing steps (if needed)

#### Missing value treatment
There are no Missing Values. No treatment is needed.

In [3]:
#Check for any missing values
df.isnull().sum().sum()

np.int64(0)

In [4]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIPCode               0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal_Loan         0
Securities_Account    0
CD_Account            0
Online                0
CreditCard            0
dtype: int64

#### Treatment of categorical variables

##### Treatment of 'ID' column
ID is a categorical variable. This does not add any mathematical meaning as each row has a unique ID. This column is dropped.

In [5]:
df_ID = df
#dropping ID column as this variable does not contribute to the model
df.drop(['ID'], axis=1, inplace=True)

##### Treatment of ZIPCode variable

In [6]:
df['ZIPCode'].nunique()

467

Zip code is given as a numericl data. However, ZIP code does not carry mathematical meaning.
ZIPCode is treated as categorical variable.
However, there are several unique values for ZIPCode.

*   Let us consider only the first two digits.
*   Convert the datatype to str (first two digits)

Then, we can use Onehot encoding on these categorical variables.

In [7]:
df['ZIPCode'] =df['ZIPCode']//1000

Feature engineering (if needed)

In [8]:
df['ZIPCode'].value_counts()

ZIPCode
94    1472
92     988
95     815
90     703
91     565
93     417
96      40
Name: count, dtype: int64

In [9]:
df.head()

,Age,Experience,Income,ZIPCode,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
0,25,1,49,91,4,1.6,1,0,0,1,0,0,0
1,45,19,34,90,3,1.5,1,0,0,1,0,0,0
2,39,15,11,94,1,1.0,1,0,0,0,0,0,0
3,35,9,100,94,1,2.7,2,0,0,0,0,0,0
4,35,8,45,91,4,1.0,2,0,0,0,0,0,1

In [10]:
df['ZIPCode'] = df['ZIPCode'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 5000 non-null   int64
 1   Experience          5000 non-null   int64
 2   Income              5000 non-null   int64
 3   ZIPCode             5000 non-null   object
 4   Family              5000 non-null   int64
 5   CCAvg               5000 non-null   float64
 6   Education           5000 non-null   int64
 7   Mortgage            5000 non-null   int64
 8   Personal_Loan       5000 non-null   int64
 9   Securities_Account  5000 non-null   int64
 10  CD_Account          5000 non-null   int64
 11  Online              5000 non-null   int64
 12  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(11), object(1)
memory usage: 507.9+ KB

In [11]:
df.head()

,Age,Experience,Income,ZIPCode,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
0,25,1,49,91,4,1.6,1,0,0,1,0,0,0
1,45,19,34,90,3,1.5,1,0,0,1,0,0,0
2,39,15,11,94,1,1.0,1,0,0,0,0,0,0
3,35,9,100,94,1,2.7,2,0,0,0,0,0,0
4,35,8,45,91,4,1.0,2,0,0,0,0,0,1

##### OneHot Encoding

In [12]:
df = pd.get_dummies(df, columns=['Education','Family','ZIPCode'])
df.head()

,Age,Experience,Income,CCAvg,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard,...,Family_2,Family_3,Family_4,ZIPCode_90,ZIPCode_91,ZIPCode_92,ZIPCode_93,ZIPCode_94,ZIPCode_95,ZIPCode_96
0,25,1,49,1.6,0,0,1,0,0,0,...,False,False,True,False,True,False,False,False,False,False
1,45,19,34,1.5,0,0,1,0,0,0,...,False,True,False,True,False,False,False,False,False,False
2,39,15,11,1.0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,True,False,False
3,35,9,100,2.7,0,0,0,0,0,0,...,False,False,False,False,False,False,False,True,False,False
4,35,8,45,1.0,0,0,0,0,0,1,...,False,False,True,False,True,False,False,False,False,False

In [13]:
df.columns

Index(['Age', 'Experience', 'Income', 'CCAvg', 'Mortgage', 'Personal_Loan',
       'Securities_Account', 'CD_Account', 'Online', 'CreditCard',
       'Education_1', 'Education_2', 'Education_3', 'Family_1', 'Family_2',
       'Family_3', 'Family_4', 'ZIPCode_90', 'ZIPCode_91', 'ZIPCode_92',
       'ZIPCode_93', 'ZIPCode_94', 'ZIPCode_95', 'ZIPCode_96'],
      dtype='object')

In [14]:
boolean_columns = df.select_dtypes(include='bool').columns
boolean_columns

Index(['Education_1', 'Education_2', 'Education_3', 'Family_1', 'Family_2',
       'Family_3', 'Family_4', 'ZIPCode_90', 'ZIPCode_91', 'ZIPCode_92',
       'ZIPCode_93', 'ZIPCode_94', 'ZIPCode_95', 'ZIPCode_96'],
      dtype='object')

In [15]:
df[boolean_columns] = df[boolean_columns].astype(int)

#### Multicollinearity Treatment

The columns 'Age' and 'Experience are highly positively correlated. It is better to drop a one of these columns to avoid multi-collinearity.
Let us drop 'Experience' column as we have previously seen some negative values as well in the original data.

In [16]:
df.drop('Experience', axis=1, inplace=True)
df.head()

,Age,Income,CCAvg,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard,Education_1,...,Family_2,Family_3,Family_4,ZIPCode_90,ZIPCode_91,ZIPCode_92,ZIPCode_93,ZIPCode_94,ZIPCode_95,ZIPCode_96
0,25,49,1.6,0,0,1,0,0,0,1,...,0,0,1,0,1,0,0,0,0,0
1,45,34,1.5,0,0,1,0,0,0,1,...,0,1,0,1,0,0,0,0,0,0
2,39,11,1.0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,35,100,2.7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,35,45,1.0,0,0,0,0,0,1,0,...,0,0,1,0,1,0,0,0,0,0

#### Outliers
*   Some of the data has outliers ('Income', 'Mortgage' and 'CCAvg')
*   However, the outliers are continuously extend beyond the right whisker. They may represent acutal data.
No outlier treatment is needed.

#### Data Imbalance


While splitting the data, stratification is needed to

*   Some of the data columns are very imbalanced
*   Stratification ensures the train test splits represent the same proportion of imbalance as the original data for accurate predictions.

In [17]:
df_orig.shape

(5000, 14)

In [18]:
df.shape

(5000, 23)

In [19]:
df['Personal_Loan'].value_counts()

Personal_Loan
0    4520
1     480
Name: count, dtype: int64

In [20]:
write_path = '../data/processed_data/Loan_Modeling_Processed_Data.csv'
df.to_csv(write_path, index=False)